package com.xworkz.employee;

import com.xworkz.employee.dto.EmployeeDTO;
import com.xworkz.employee.enums.Role;

public class EmployeeRunner {
    public static void main(String[] args) {
        System.out.println("Main method started...");

        // Using the AllArgsConstructor generated by Lombok
        EmployeeDTO emp = new EmployeeDTO(1, "Abhishek", Role.DEVELOPER);

        // Even though we didn't write Getters, we can call them!
        System.out.println("Invoking getName: " + emp.getName());
        System.out.println("Invoking getRole: " + emp.getRole());

        //  Changing data using Lombok's generated Setter
        emp.setName("Abhishek Kumar");

        // Printing object using Lombok's @ToString
        System.out.println("Employee Data: " + emp.toString());

        System.out.println("Main method ended.");
    }
}