package com.xworkz.home;

import com.xworkz.home.dto.SmartDeviceDTO;
import com.xworkz.home.enums.DeviceType;

public class DeviceRunner {

    public static void main(String[] args) {
        System.out.println("Main method started...");

        // Creating a new Smart Device using AllArgsConstructor
        SmartDeviceDTO light = new SmartDeviceDTO("IOT-101", "Philips Hue", DeviceType.LIGHT, true, 9.5);

        // Accessing data using Getters generated by @Data
        System.out.println("Invoking getModelName: " + light.getModelName());
        System.out.println("Is Device Online? " + light.isOnline());

        // Changing status using Setter generated by @Data
        light.setOnline(false);
        light.setPowerConsumption(0.0);

        // Printing the full state using @Data's toString
        System.out.println("Updated Device State: " + light.toString());

        // Creating another object to test Equality
        SmartDeviceDTO light2 = new SmartDeviceDTO("IOT-101", "Philips Hue", DeviceType.LIGHT, false, 0.0);

        // Testing .equals() generated by @Data
        boolean isEqual = light.equals(light2);
        System.out.println("Are both devices identical? " + isEqual);

        System.out.println("Main method ended.");
    }
}
